name: Playwright Tests
on:
  push:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: 50:50
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: gradle build -x test
      - name: Test
        run: cd ./ && git clone https://github.com/LeviBekerman/PlaywrightGradle.git && cd PlaywrightGradle && gradle test
