name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull: 'https://github.com/LeviBekerman/PlaywrightGradle.git'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: gradle build -x test
      - name: Test
        run: gradle test